package main

import (
	"github.com/opensearch-service-serverless/mcp-server/config"
	"github.com/opensearch-service-serverless/mcp-server/models"
	tools_x_amz_target_opensearchserverless_createcollection "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_createcollection"
	tools_x_amz_target_opensearchserverless_listvpcendpoints "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listvpcendpoints"
	tools_x_amz_target_opensearchserverless_deletevpcendpoint "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_deletevpcendpoint"
	tools_x_amz_target_opensearchserverless_deletesecuritypolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_deletesecuritypolicy"
	tools_x_amz_target_opensearchserverless_createvpcendpoint "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_createvpcendpoint"
	tools_x_amz_target_opensearchserverless_createsecuritypolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_createsecuritypolicy"
	tools_x_amz_target_opensearchserverless_listsecurityconfigs "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listsecurityconfigs"
	tools_x_amz_target_opensearchserverless_listsecuritypolicies "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listsecuritypolicies"
	tools_x_amz_target_opensearchserverless_getaccesspolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_getaccesspolicy"
	tools_x_amz_target_opensearchserverless_updatesecurityconfig "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updatesecurityconfig"
	tools_x_amz_target_opensearchserverless_listtagsforresource "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listtagsforresource"
	tools_x_amz_target_opensearchserverless_listaccesspolicies "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listaccesspolicies"
	tools_x_amz_target_opensearchserverless_batchgetvpcendpoint "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_batchgetvpcendpoint"
	tools_x_amz_target_opensearchserverless_deletesecurityconfig "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_deletesecurityconfig"
	tools_x_amz_target_opensearchserverless_updateaccountsettings "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updateaccountsettings"
	tools_x_amz_target_opensearchserverless_deletecollection "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_deletecollection"
	tools_x_amz_target_opensearchserverless_updatesecuritypolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updatesecuritypolicy"
	tools_x_amz_target_opensearchserverless_untagresource "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_untagresource"
	tools_x_amz_target_opensearchserverless_createsecurityconfig "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_createsecurityconfig"
	tools_x_amz_target_opensearchserverless_getaccountsettings "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_getaccountsettings"
	tools_x_amz_target_opensearchserverless_listcollections "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_listcollections"
	tools_x_amz_target_opensearchserverless_getsecuritypolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_getsecuritypolicy"
	tools_x_amz_target_opensearchserverless_updateaccesspolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updateaccesspolicy"
	tools_x_amz_target_opensearchserverless_batchgetcollection "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_batchgetcollection"
	tools_x_amz_target_opensearchserverless_getpoliciesstats "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_getpoliciesstats"
	tools_x_amz_target_opensearchserverless_updatecollection "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updatecollection"
	tools_x_amz_target_opensearchserverless_createaccesspolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_createaccesspolicy"
	tools_x_amz_target_opensearchserverless_deleteaccesspolicy "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_deleteaccesspolicy"
	tools_x_amz_target_opensearchserverless_tagresource "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_tagresource"
	tools_x_amz_target_opensearchserverless_getsecurityconfig "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_getsecurityconfig"
	tools_x_amz_target_opensearchserverless_updatevpcendpoint "github.com/opensearch-service-serverless/mcp-server/tools/x_amz_target_opensearchserverless_updatevpcendpoint"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_opensearchserverless_createcollection.CreateCreatecollectionTool(cfg),
		tools_x_amz_target_opensearchserverless_listvpcendpoints.CreateListvpcendpointsTool(cfg),
		tools_x_amz_target_opensearchserverless_deletevpcendpoint.CreateDeletevpcendpointTool(cfg),
		tools_x_amz_target_opensearchserverless_deletesecuritypolicy.CreateDeletesecuritypolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_createvpcendpoint.CreateCreatevpcendpointTool(cfg),
		tools_x_amz_target_opensearchserverless_createsecuritypolicy.CreateCreatesecuritypolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_listsecurityconfigs.CreateListsecurityconfigsTool(cfg),
		tools_x_amz_target_opensearchserverless_listsecuritypolicies.CreateListsecuritypoliciesTool(cfg),
		tools_x_amz_target_opensearchserverless_getaccesspolicy.CreateGetaccesspolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_updatesecurityconfig.CreateUpdatesecurityconfigTool(cfg),
		tools_x_amz_target_opensearchserverless_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_opensearchserverless_listaccesspolicies.CreateListaccesspoliciesTool(cfg),
		tools_x_amz_target_opensearchserverless_batchgetvpcendpoint.CreateBatchgetvpcendpointTool(cfg),
		tools_x_amz_target_opensearchserverless_deletesecurityconfig.CreateDeletesecurityconfigTool(cfg),
		tools_x_amz_target_opensearchserverless_updateaccountsettings.CreateUpdateaccountsettingsTool(cfg),
		tools_x_amz_target_opensearchserverless_deletecollection.CreateDeletecollectionTool(cfg),
		tools_x_amz_target_opensearchserverless_updatesecuritypolicy.CreateUpdatesecuritypolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_opensearchserverless_createsecurityconfig.CreateCreatesecurityconfigTool(cfg),
		tools_x_amz_target_opensearchserverless_getaccountsettings.CreateGetaccountsettingsTool(cfg),
		tools_x_amz_target_opensearchserverless_listcollections.CreateListcollectionsTool(cfg),
		tools_x_amz_target_opensearchserverless_getsecuritypolicy.CreateGetsecuritypolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_updateaccesspolicy.CreateUpdateaccesspolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_batchgetcollection.CreateBatchgetcollectionTool(cfg),
		tools_x_amz_target_opensearchserverless_getpoliciesstats.CreateGetpoliciesstatsTool(cfg),
		tools_x_amz_target_opensearchserverless_updatecollection.CreateUpdatecollectionTool(cfg),
		tools_x_amz_target_opensearchserverless_createaccesspolicy.CreateCreateaccesspolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_deleteaccesspolicy.CreateDeleteaccesspolicyTool(cfg),
		tools_x_amz_target_opensearchserverless_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_opensearchserverless_getsecurityconfig.CreateGetsecurityconfigTool(cfg),
		tools_x_amz_target_opensearchserverless_updatevpcendpoint.CreateUpdatevpcendpointTool(cfg),
	}
}
